### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by kra53n** [kra53n/md#1]
- [ ] render to html all github Markdown dialect
- [ ] mobile viewing support
- [ ] render from rendered html to pdf in Firefox, Edge, Chrome browsers
